# Generated by Django 4.2.6 on 2023-11-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('type', models.CharField(choices=[('image', 'image'), ('video', 'video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/images/', verbose_name='Image file')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Upload video on Youtube and paste link here (NOTE: If video, then also upload image for thumbnail)')),
                ('rank', models.IntegerField(default=1)),
                ('hidden', models.BooleanField(blank=True, default=False, verbose_name='Hide')),
            ],
        ),
    ]
