# Generated by Django 4.2.6 on 2023-11-03 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('gmail_link', models.EmailField(blank=True, max_length=254, null=True)),
                ('vertical_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.verticalposition')),
            ],
            options={
                'unique_together': {('vertical_position', 'name')},
            },
        ),
    ]
