# Generated by Django 4.2.6 on 2023-11-05 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designationName', models.CharField(max_length=100)),
                ('rank', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PastTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads/team/')),
                ('github_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(blank=True, max_length=100, null=True)),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads/team/')),
                ('github_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(blank=True, max_length=100, null=True)),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.designation')),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='VerticalPosition',
        ),
    ]
