# Generated by Django 4.2.6 on 2023-11-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.PositiveIntegerField(choices=[(1, 'Title Sponsor'), (2, 'Associate Sponsor'), (3, 'Online Media Sponsor'), (4, 'Consultancy Partner'), (5, 'Technical Events Partner'), (6, 'VC Partner'), (7, 'Workshop Partner'), (8, 'Services Partner'), (9, 'Entertainment Partner'), (10, 'Giftings Partner'), (11, 'Digital Media Partner'), (12, 'Printing Partner'), (13, 'Media Partner'), (14, 'Merchandise Partner')], default=1)),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
