# Generated by Django 4.2.6 on 2023-11-05 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_type', models.CharField(max_length=100, verbose_name='Sponsor Type')),
                ('rank', models.IntegerField(verbose_name='hierarchical position of the title')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sponsors/', verbose_name='sponsors Logo')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sponsor name')),
                ('sponsor_link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link to Sponsors website')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsors.sponsordesignation')),
            ],
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
