# Generated by Django 4.2.6 on 2023-11-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('endDate', models.DateField()),
                ('endTime', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
            ],
        ),
    ]
