# Generated by Django 4.2.6 on 2023-11-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='endDate',
        ),
    ]
