# Generated by Django 4.2.6 on 2023-11-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preregister',
            old_name='CA',
            new_name='isCA',
        ),
    ]
