# Generated by Django 4.2.6 on 2023-11-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('prizeMoney', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('eventType', models.CharField(max_length=255)),
                ('rulebookLink', models.URLField(blank=True, null=True)),
                ('isSpeaker', models.BooleanField()),
                ('unstopLink', models.URLField(blank=True, null=True)),
                ('eventLocation', models.CharField(max_length=255)),
                ('sponsorLinks', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
