# Generated by Django 4.2.6 on 2023-11-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('updatestype', models.CharField(choices=[('event', 'Event'), ('app', 'App')], max_length=5)),
                ('news', models.TextField()),
            ],
        ),
    ]
